apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd

data:
  trigger.on-health-degraded: |
    - when: app.status.health.status == 'Degraded'
      send: [app-alert]

  trigger.on-sync-outofsync: |
    - when: app.status.sync.status == 'OutOfSync'
      send: [app-alert]

  template.app-alert: |
    message: |
      Application: {{.app.metadata.name}}
      Environment: production
      Status: {{.app.status.health.status}}

      ArgoCD:
      https://argocd.example.com/applications/{{.app.metadata.name}}
